### ISSUE TITLE
Legit version on the Chrome store?

### ISSUE THREAD

**Issue by neiffer** [zlwaterfield/scramble#11]
Hey Zach... is this:

https://chromewebstore.google.com/detail/scramble/mkaljgnigabhmjfookbokejhfghmkffo

legit?

**Comment by zlwaterfield** [comment]
Yeah but it doesn't work, will update to the latest version this week

**Comment by ully-lab** [comment]
I tried it but it won't allow me to save the api key. Let us know when it's sorted Zach, thanks

**Comment by zlwaterfield** [comment]
@ully-lab can you send more info and I'll look into it this week.

**Comment by Shrhawk** [comment]
<img width="1784" alt="Screenshot 2024-10-22 at 1 37 34 PM" src="https://github.com/user-attachments/assets/463e2e74-1738-40e7-9775-329f3a59104b">
same issue @zlwaterfield

**Comment by zlwaterfield** [comment]
Sorry guys! Fixed on main and submitted a new version (1.2) to Chrome store, should be live in a few days.

**Comment by ully-lab** [comment]
that's great Zach, I'll check it out in couple of days and let you know. thanks

**Comment by ully-lab** [comment]
its working for me now, api key saved correctly. will use it now instead of grammarly and see how it goes. thanks
