### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by divaltor** [zlwaterfield/scramble#2]
Is that possible to add support for Firefox browser? Thanks

**Comment by tcsenpai** [comment]
Upping this. I am not sure of what it takes for an extension to be converted to Firefox, but I guess most of the core code would remain the same

**Comment by zlwaterfield** [comment]
This should be done now. Can you try now @divaltor?

**Comment by bearjaws** [comment]
I am trying to install it on Firefox, but I do not see a great way to import it. I built the Tailwindcss file and when I import I get  "background.service_worker is currently disabled"

Googling that shows Firefox doesn't support service workers from MV3, but I feel like I am missing something simple.

**Comment by zlwaterfield** [comment]
Fixed and updated the docs!

**Comment by PeterDaveHello** [comment]
Will this extension be published on addons.mozilla.org? I checked the README.md but it's still "coming soon" :smile:

**Comment by zlwaterfield** [comment]
Looking into it! It's very buggy and I can't get my account created ...

**Comment by bearjaws** [comment]
Thanks @zlwaterfield the new instructions work great for Firefox.

**Comment by Jatin794** [comment]
If it's working can we have an .xpi file at least, considering sideloading addons is easier in firefox?
