### ISSUE TITLE
Doesn't work in Gmail & JIRA reply field?

### ISSUE THREAD

**Issue by regstuff** [zlwaterfield/scramble#4]
Hi
Thanks for the extension. I'm able to get responses with "regular text" on webpages.
But when I choose one of the scramble options on text that is being written in a comment/reply field in JIRA or gmail, there is no response.
It does generate a response in this Github comment field. But I am unable to edit the response.
Is it supposed to work in such situations also?

Here's a screenshot of where it doesnt work.

![image](https://github.com/user-attachments/assets/869ee0e8-e475-4075-8d8a-f803cd3e83fe)

**Comment by zlwaterfield** [comment]
This should be working now, can you try and let me know?
