### ISSUE TITLE
Is it API Key or Project Key?

### ISSUE THREAD

**Issue by zhenghao1** [zlwaterfield/scramble#8]
OpenAI now seems to have the concept of "Project API Keys".  The old "User API Keys" is a legacy feature now.  Can you state clearly (preferably with screenshots) how to obtain this key for Scramble to work.  I tried both types of keys and they both failed.

![image](https://github.com/user-attachments/assets/477c9ac6-1754-4f3a-8575-ef7ee85068df)

**Comment by zlwaterfield** [comment]
API Key
